//* list types
const ADD_ELEMENTO = "ADD-ELEMENTO";
const TOGGLE_ELEMENTO = "TOGGLE-ELEMENTO";
const DELETE_ELEMENTO = "DELETE-ELEMENTO";

//* nombre types
const MODIFY_NOMBRE = "MODIFICAR-NOMBRE";
const DELETE_NOMBRE = "ELIMINAR-NOMBRE";

// * modal lista item types
const OPEN_MODAL = "ABRIR-MODAL";
const CLOSE_MODAL = "CERRAR-MODAL";

//* Rutas types
const SET_ACTUAL_ROUTE ="SET-ACTUAL-ROUTE"

export {
  DELETE_NOMBRE,
  ADD_ELEMENTO,
  TOGGLE_ELEMENTO,
  DELETE_ELEMENTO,
  MODIFY_NOMBRE,
  OPEN_MODAL,
  CLOSE_MODAL,
  SET_ACTUAL_ROUTE
};
